version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception_network
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception_network
    tty: true

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

networks:
  inception_network:
    driver: bridge